### ISSUE TITLE
Adding congressional districts to maps

### ISSUE THREAD

**Issue by raheem03** [UrbanInstitute/urbnmapr#39]
First, I'm new to collaborating with others in this way, so apologies for submitting the pull request before consulting. Figured we'd be able to discuss this (one way or the other) as part of that process. But it seems like the convention is to discuss first and, if that's accurate, sorry for not recognizing that!

In addition to states and counties, congressional districts seem useful and easy to implement. (while Census makes blocks and tracts available, they are trickier since they are much more massive and require being downloaded by state). This feels like low-hanging fruit.

Is this something that could be useful?

**Comment by sstrochak** [comment]
Hi Raheem! Thanks so much for contributing. 

We have had discussions about adding more geographies, but we are also trying to limit the size of the package. Our vision was that further geographies will be function-driven- in this case, we would write a function that would download and transform the congressional district shapefiles, instead of storing them directly in the package like we did for the `states` and `counties` objects.

If this is something you'd be interested in working on, that would be awesome! Congressional districts do seem like a logical next step for urbnmapr.

**Comment by raheem03** [comment]
That makes a lot of sense. 

The way I can imagine operationalizing this is to write a function in `utils` that checks to see if a geographic level has been downloaded (e.g., congressional districts) in a user's data directory, which is defined by `rappdirs`. If it has, the program goes ahead and loads the shapefile. If it hasn't, we first download the shapefile into the data directory (primarily relying on `get_shapefile()` to do the heavy lifting).

If you're reluctant to add another dependency (`rappdirs`), the alternative would be to let users set where they want to save the shapefiles, but this might mean having to create environment variables so the program knows where to look for the new shapefiles later.

If this sounds good to you, I'm happy to try and implement this.
